apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stress-app
  name: stress-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stress-app
  template:
    metadata:
      labels:
        app: stress-app
    spec:
      containers:
      - image: busybox
        name: busybox
        resources:
          limits:
            cpu: "0.5"
        command: ["dd", "if=/dev/zero", "of=/dev/null"]

