version: "3"
services:
  mysql:
    build: .
    image: mysql_org
    container_name: mysql_demo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: Asia/Tokyo
    ports:
      - 13306:3306
    volumes:
      - ~/work/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ~/work/mysql/db:/var/lib/mysql
