version: "3"
services:
  mysql:
    build: .
    image: mysql_org
    container_name: mysql_demo
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
    - ~/work/mysql:/var/lib/mysql
    ports:
    - 3306:3306
